### ISSUE TITLE
Plugin 'weathermap': Uncaught DivisionByZeroErro

### ISSUE THREAD

**Issue by jdcoats** [thurban/plugin_weathermap#121]
```
2023/07/20 15:42:12 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
2023/07/20 15:42:12 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2023/07/20 15:42:12 - ERROR PHP ERROR in Plugin 'weathermap': Uncaught DivisionByZeroError: Division by zero in /var/www/localhost/htdocs/cacti/plugins/weathermap/setup.php:1070 Stack trace: #0 /var/www/localhost/htdocs/cacti/lib/plugins.php(276): weathermap_poller_output(Array) #1 /var/www/localhost/htdocs/cacti/lib/plugins.php(155): api_plugin_run_plugin_hook_function('poller_output', 'weathermap', 'weathermap_poll...', Array) #2 /var/www/localhost/htdocs/cacti/lib/poller.php(812): api_plugin_hook_function('poller_output', Array) #3 /var/www/localhost/htdocs/cacti/lib/poller.php(831): process_poller_output(Resource id #68, 40000) #4 /var/www/localhost/htdocs/cacti/poller.php(762): process_poller_output(Resource id #68, true) #5 {main} thrown in file: /var/www/localhost/htdocs/cacti/plugins/weathermap/setup.php on line: 1070
```

**Comment by TheWitness** [comment]
Test the latest setup.php @jdcoats
