### ISSUE TITLE
weathermap crash after upgrade and path changes

### ISSUE THREAD

**Issue by dallenk** [thurban/plugin_weathermap#164]
perhaps a regression of https://github.com/Cacti/plugin_weathermap/issues/129 ??

upgraded this morning after not using weathermap on this system for a while, dealing with database performance issues.  Typo on my part... FYI... a G and an M after 512 makes a HUGE difference to MariaDB :)

anywhoo..  see the new paths for config.php and updated outside of the cacti dir.. permissions set to www-data.  Plugin will enable, but on first run it crashes and disables itself.  tried full un-install/re-install. disabled all configs and only enabled the simple.conf with very limited instruction.

`
$configdir = '/var/www/html/cacti-weathermap/configs/';
$outputdir = '/var/www/html/cacti-weathermap/output/';
`

current versions:
commit 582f4f6c1a31cc17c382a6be83a2a40894fbe323 (HEAD -> develop, origin/develop, origin/HEAD)
Author: TheWitness <thewitness@cacti.net>
Date:   Mon Dec 9 11:24:18 2024 -0500

Plugin: /var/www/html/cacti/plugins/weathermap/
commit d30f39ea79abcc84c86215445d084c72bbe2c5a1 (HEAD -> develop, origin/develop, origin/HEAD)
Author: TheWitness <thewitness@cacti.net>
Date:   Wed Nov 20 14:18:01 2024 -0500

**php is at 8.1. perhaps this is an 8.2 issue?  intl is installed and everything up-to-date as of this morning**

error (word wrap on the post doesn't seem to be working for some reason for me)
```
2024-12-09 08:58:49 - SQL Backtrace: (/plugins/weathermap/weathermap-cacti-plugin-mgmt.php[286]:add_config(), /plugins/weathermap/weathermap-cacti-plugin-mgmt.php[1567]:db_execute_prepared())

2024-12-09 08:58:49 - CMDPHP ERROR: A DB Exec Failed!, Error: Duplicate entry 'simple.conf' for key 'configfile'

2024-12-09 08:58:16 - MAILER INFO: Mail successfully sent via SMTP from '911 Network Monitor <techs@domain.ca>', to 'Administrator <admin@domain.ca>', cc '', bcc '', and took 1.46 seconds, Subject 'Cacti System Warning'

2024-12-09 08:58:15 - SYSTEM MONITOR STATS: Time:0.02 Reboots:0 DownDevices:0 Notifications:0 Purges:0
2024-12-09 08:58:15 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
2024-12-09 08:58:15 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-09 08:58:15 - ERROR PHP ERROR in Plugin 'weathermap': Uncaught Error: Found unconstructed IntlDateFormatter in /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php:1947 Stack trace: #0 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(1947): IntlDateFormatter->format() #1 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2043): WeatherMap->{closure}() #2 [internal function]: WeatherMap->{closure}() #3 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2045): preg_replace_callback() #4 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2053): WeatherMap->strftime() #5 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(3646): WeatherMap->DrawTimestamp() #6 /var/www/html/cacti/plugins/weathermap/lib/poller-common.php(461): WeatherMap->DrawMap() #7 /var/www/html/cacti/plugins/weathermap/setup.php(1233): weathermap_run_maps() #8 /var/www/html/cacti/lib/plugins.php(243): weathermap_poller_bottom() #9 /var/www/html/cacti/lib/plugins.php(97): api_plugin_run_plugin_hook() #10 /var/www/html/cacti/poller.php(991): api_plugin_hook() #11 {main} thrown in file: /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 1947
```

**Comment by TheWitness** [comment]
Run `php -m` is php-intl installed?  It could be as I have not been working on the Weathermap for a while.  Distracted with the core.  Pull requests are always welcome.

**Comment by dallenk** [comment]
It is installed and current, I'll see what I can do and if I can fix I'll try a pull request.

**Comment by TheWitness** [comment]
I'm going to close this as we reverted this change.  @netniV is trying to re-introduce it with some WeatherMap changes he is proposing.
