### ISSUE TITLE
not a bug just dumb I guess! Weathermap 98a to 1.3.1

### ISSUE THREAD

**Issue by edjchristopher** [thurban/plugin_weathermap#166]
I must be missing something, so let me say I am sorry to waste anyone's time. But I have been using Cacti and weathermaps
for quite a while, and I cannot see clear instructions on how to "upgrade" the weathermap plugin from 098a to v1.3.1. I have tested in non-prod, by disabling the plugin (DO NOT UNINSTALL), from the Linux console mv weathermap weathermap-old
copy the full repo (v1.3.1 dev) to weathermap folder and in the gui enable the new v1.3.1 weathermap. Obviously when I rename the 098a weathermap all of my current maps are in that folder structure. How to I convert them to this new version? Sorry to be a bonehead!

**Comment by TheWitness** [comment]
@edjchristopher, I'll have time to work on multiple issues after I wind down on Cacti 1.3 projects.  I hope you will have time to collaborate as I don't have a real good use case for the tool in my home office.

**Comment by edjchristopher** [comment]
Sure I can help.

I was hopeful I could get weathermap v1.3.1 migration instructions as I cannot find any other than very old versions.

**Comment by edjchristopher** [comment]
Just reach out when you are ready!!

**Comment by edjchristopher** [comment]
@TheWitness Sure I can help.

I was hopeful I could just get weathermap v1.3.1 migration instructions as I cannot find any other than very old versions.

**Comment by TheWitness** [comment]
What time zone are you in?

**Comment by edjchristopher** [comment]
Eastern time zone

**Comment by TheWitness** [comment]
Okay, perfect.

**Comment by edjchristopher** [comment]
OK so. I have never had any problems with Cacti, yet I cannot get this plugin to work. I have replicated our Prod Cacti which was a repo install 1.2.27. Add in this weathermap plugin v1.3.1 it looks like it did ok. I cannot create a new map even. So I blew away that server and did a fresh install 1.2.27 (repo again) with weathermap v1.3.1 and get the same results. Looks ok but will not function, even creating a new map.

Is it possible it may be the repo install? Should I just get your download and do it all over again?

Thoughts?? I assume this is working somewhere?!?

**Comment by TheWitness** [comment]
Bring up your browsers debug page and see if you see any JavaScript errors.  Also check the Cacti log for errors.  When you upgrade, Cacti will attempt to move asset's to new folders, so you have to make sure that the apache has full access to the plugin directory.  If you pull the develop version, won't be able to install until you relocate the config.php.dist and move your output and config folders out of the plugin directory if you can manage it.

**Comment by TheWitness** [comment]
There could be bugs in that last bit.  Good thing it's not production.

**Comment by edjchristopher** [comment]
@TheWitness still working on getting the new weathermap to work. I am getting these 2 PHP errors ... make any sense??
php 8.2.27

2025-01-03 19:21:14 - ERROR PHP ERROR in Plugin 'weathermap': Uncaught Error: Call to undefined function weathermap_determine_config() in /var/www/html/cacti/plugins/weathermap/weathermap-cacti-plugin.php:49 Stack trace: #0 {main} thrown in file: /var/www/html/cacti/plugins/weathermap/weathermap-cacti-plugin.php on line: 49
--
2025-01-03 19:13:23 - ERROR PHP ERROR in Plugin 'weathermap': Uncaught ValueError: imagecolorexact(): Argument #2 ($red) must be between 0 and 255 (inclusive) in /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.functions.php:367 Stack trace: #0 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.functions.php(367): imagecolorexact() #1 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.functions.php(1817): myimagecolorallocate() #2 /var/www/html/cacti/plugins/weathermap/lib/WeatherMapNode.class.php(657): Colour->gdallocate() #3 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(3606): WeatherMapNode->pre_render() #4 /var/www/html/cacti/plugins/weathermap/lib/poller-common.php(461): WeatherMap->DrawMap() #5 /var/www/html/cacti/plugins/weathermap/setup.php(1233): weathermap_run_maps() #6 /var/www/html/cacti/lib/plugins.php(237): weathermap_poller_bottom() #7 /var/www/html/cacti/lib/plugins.php(95): api_plugin_run_plugin_hook() #8 /var/www/html/cacti/poller.php(941): api_plugin_hook() #9 {main} thrown in file: /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.functions.php on line: 367

**Comment by TheWitness** [comment]
Use the previous tag.  I have a version that is in flight, but I won't be able to work on it till I have Cacti 1.3 ready for alpha/beta.

**Comment by alcatron** [comment]
I wouldnt bother going to anything newer, I still run Cacti 1.2.17 and weathermap 0.98a because anything after just becomes so broken, a real investment will take fixing the new weathermap versions to work like 0.98a and the newer cacti versions

**Comment by TheWitness** [comment]
Going to close this one.
