### ISSUE TITLE
weathermap disabled - Uncaught Error: Class "index" not found

### ISSUE THREAD

**Issue by esanders83** [thurban/plugin_weathermap#52]
Hello,
I'm running the following:
- Ubuntu 22.04.1 LTS (jammy)
- PHP 8.1.2 (apt stock)
- NGINX 1.18 (apt stock)
- Cacti 1.3.0(git clone -> dev eaefda08)

I installed weathermap from git clone (https://github.com/Cacti/plugin_weathermap.git), changed permissions, and I enabled/install the plugin. Once I start trying to add a map Weathermap crashes and the cacti.log shows:

```
2023-01-17 14:40:07 - ERROR PHP WARNING in  Plugin 'weathermap': Cannot modify header information - headers already sent by (output started at /var/www/html/cacti/lib/functions.php:1543) in file: /var/www/html/cacti/plugins/weathermap/lib/datasources/index.php  on line: 42
2023-01-17 14:40:07 - CMDPHP PHP ERROR WARNING Backtrace:  (/poller.php[863]:api_plugin_hook(), /lib/plugins.php[89]:api_plugin_run_plugin_hook(), /lib/plugins.php[237]:weathermap_poller_bottom(), /plugins/weathermap/setup.php[1111]:weathermap_run_maps(), /plugins/weathermap/lib/poller-common.php[360]:WeatherMap->__construct(), /plugins/weathermap/lib/WeatherMap.class.php[372]:WeatherMap->Reset(), /plugins/weathermap/lib/WeatherMap.class.php[529]:WeatherMap->LoadPlugins(), /plugins/weathermap/lib/WeatherMap.class.php[822]:include_once(), /plugins/weathermap/lib/datasources/index.php[42]:header(), CactiErrorHandler())
2023-01-17 14:40:07 - ERROR PHP ERROR in  Plugin 'weathermap': Uncaught Error: Class "index" not found in /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php:841 Stack trace: #0 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(529): WeatherMap->LoadPlugins() #1 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(372): WeatherMap->Reset() #2 /var/www/html/cacti/plugins/weathermap/lib/poller-common.php(360): WeatherMap->__construct() #3 /var/www/html/cacti/plugins/weathermap/setup.php(1111): weathermap_run_maps() #4 /var/www/html/cacti/lib/plugins.php(237): weathermap_poller_bottom() #5 /var/www/html/cacti/lib/plugins.php(89): api_plugin_run_plugin_hook() #6 /var/www/html/cacti/poller.php(863): api_plugin_hook() #7 {main} thrown in file: /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 841
2023-01-17 14:40:07 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2023-01-17 14:40:07 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
```

What else I can provide to help troubleshoot this?

Thank you!
eric

**Comment by TheWitness** [comment]
Did you install this over a pre-existing install of Weathermap?  If so, move the lib folder out of the way, and copy the lib folder fresh from the cacti repo version.

**Comment by esanders83** [comment]
Hello,
This was a fresh install of Cacti and weathermap.  Sorry, I accidentally closed this incident😞

**Comment by esanders83** [comment]
.

**Comment by TheWitness** [comment]
Okay, now I know why you are experiencing this as well as others fixing now.  Helps reading the tickets on a PC and not one your phone.  Old age and no glasses ;)

**Comment by TheWitness** [comment]
Try out this patch as it may take a day or two to get merged.

https://github.com/Cacti/plugin_weathermap/pull/54

**Comment by esanders83** [comment]
Hello again,
I applied the patch and it worked without any errors or reverting to disabled plugin.  

Thank you for your help on this!
eric

**Comment by netniV** [comment]
Updated the formatting in the original post, the solution looks good.
