### ISSUE TITLE
gettext error

### ISSUE THREAD

**Issue by guebli** [thurban/plugin_weathermap#83]
When upgrading  php from 7.4 to 8.1, we have this error

```
<html><body>
<!--StartFragment-->

03/Feb/2023 11:21:20 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
03/Feb/2023 11:21:20 - ERROR PHP ERROR: Uncaught  InvalidArgumentException: Select_string only accepts integers: 1 in  /usr/local/share/cacti/include/vendor/phpgettext/gettext.php:354 Stack  trace: #0  /usr/local/share/cacti/include/vendor/phpgettext/gettext.php(388):  gettext_reader->select_string('1') #1  /usr/local/share/cacti/include/global_languages.php(482):  gettext_reader->ngettext('1 User', '1 Users', '1') #2  /usr/local/share/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php(1062):  __n('1 User', '1 Users', '1', 'weathermap') #3  /usr/local/share/cacti/plugins/weathermap/weathermap-cacti-plugin-mgmt.php(323):  maplist() #4 {main} thrown in file:  /usr/local/share/cacti/include/vendor/phpgettext/gettext.php on line:  354

<!--EndFragment-->
</body>
</html>

Weathermap Pre-install Checker

This page checks for some common problems with your PHP and 
server environment that may stop Weathermap or the Editor from working.</p>
NOTE: You should run this script as a web page AND from the command-line, as the environment can be different in each.

PHP Basics

	This is the PHP version that is responsible for
	
		The web-based editor
		Building maps with Rebuild Now from Cacti
	

	<p>This is PHP Version 8.1.14 running on "FreeBSD monitor 
12.3-RELEASE-p6 FreeBSD 12.3-RELEASE-p6 GENERIC amd64" with a 
memory_limit of '512M'. (Ok)</p>
	<p>The php.ini file was </p>
	<p>
The following additional ini files were read:

/usr/local/etc/php/ext-18-session.ini,
/usr/local/etc/php/ext-20-bz2.ini,
/usr/local/etc/php/ext-20-ctype.ini,
/usr/local/etc/php/ext-20-curl.ini,
/usr/local/etc/php/ext-20-dom.ini,
/usr/local/etc/php/ext-20-fileinfo.ini,
/usr/local/etc/php/ext-20-filter.ini,
/usr/local/etc/php/ext-20-gd.ini,
/usr/local/etc/php/ext-20-gettext.ini,
/usr/local/etc/php/ext-20-gmp.ini,
/usr/local/etc/php/ext-20-iconv.ini,
/usr/local/etc/php/ext-20-intl.ini,
/usr/local/etc/php/ext-20-ldap.ini,
/usr/local/etc/php/ext-20-mbstring.ini,
/usr/local/etc/php/ext-20-mcrypt.ini,
/usr/local/etc/php/ext-20-mysqli.ini,
/usr/local/etc/php/ext-20-pcntl.ini,
/usr/local/etc/php/ext-20-pdo.ini,
/usr/local/etc/php/ext-20-pgsql.ini,
/usr/local/etc/php/ext-20-phar.ini,
/usr/local/etc/php/ext-20-posix.ini,
/usr/local/etc/php/ext-20-simplexml.ini,
/usr/local/etc/php/ext-20-snmp.ini,
/usr/local/etc/php/ext-20-sockets.ini,
/usr/local/etc/php/ext-20-sqlite3.ini,
/usr/local/etc/php/ext-20-tokenizer.ini,
/usr/local/etc/php/ext-20-xml.ini,
/usr/local/etc/php/ext-20-xmlwriter.ini,
/usr/local/etc/php/ext-20-zip.ini,
/usr/local/etc/php/ext-20-zlib.ini,
/usr/local/etc/php/ext-30-pdo_mysql.ini
</p>

	PHP Functions

Some parts of Weathermap need special support in your PHP installation to work.</p>
    This PHP uses the system GD library, which MIGHT have alpha-blending
 bugs. Check that you have at least GD 2.0.34 installed, if you see 
problems with weathermap segfaulting.

You can test for this specific fault by running check-gdbug.php
	

imagepng() |  
-- | --
imagecreatetruecolor() |  
imagealphablending() |  
imageSaveAlpha() |  
preg_match() |  
imagecreatefrompng() |  
imagecreatefromjpeg() |  
imagecreatefromgif() |  
imagejpeg() |  
imagegif() |  
imagecopyresampled() |  
imagettfbbox() |  
memory_get_usage() |  

OK! Your PHP and server environment *seems* to have support for ALL of the
Weathermap features. Make sure you have run this script BOTH as a web page
and from the CLI to be sure, however.
```

**Comment by TheWitness** [comment]
This is a Cacti issue. Please move up to 1.2.x of Cacti and if the issue persists, we can re-open this.

**Comment by Gabrielx117** [comment]
I got the same error on cacti 1.2.23. the php version is 8.1.

> This is a Cacti issue. Please move up to 1.2.x of Cacti and if the issue persists, we can re-open this.

**Comment by TheWitness** [comment]
Yea, we are days out from 1.2.24, and this issue is addressed.
